traj_chosen_topic: '~traj_chosen'

debug:
    ip_topic: 'car_pose'
    update_trajectory_rate: 2
    flag:
        viz_traj_chosen_trace: false
        rollouts_on_init_pose: true
        viz_rollouts: true
    viz_rollouts:
        n: -1
        print_stats: true
