traj_chosen_topic: '/rhcontroller/traj_chosen'
use_sim_pose: false
use_odom_pose: true

debug:
    ip_topic: '/sim_car_pose/pose'
    update_trajectory_rate: 2
    flag:
        viz_traj_chosen_trace: false
        rollouts_on_init_pose: true
        viz_rollouts: true
    viz_rollouts:
        n: 10
        print_stats: true
