traj_chosen_topic: '/rhcontroller/traj_chosen'

trajgen:
  trajgen_name: tl

debug:
    ip_topic: '/pf/inferred_pose'
    flag:
        viz_rollouts: true
        current_path: true
        viz_traj_chosen: true
        viz_cost_fn: true
    viz_rollouts:
        n: -1
        print_stats: false
    traj_chosen_trace:
        rate: 1
